"""`vd plan` — the decision engine. Input: `Snapshot` + `Policy`. Output: exactly one
`Action` (its `kind` may be `noop`/`escalate`/`halt` — see `Action.is_onchain()`).

Ladder, first match wins, exactly as docs/SPEC.md §5.4 specifies:

```
0. KILLSWITCH present                -> HALT
1. /health not ok                    -> NO-OP, reason recorded (unless positively
                                         confirmed randomness/combat-only -- see
                                         Snapshot.combat_only_degradation, 2026-08-22)
1b. gameMaintenance.paused           -> ESCALATE (or NO-OP if escalation.on_game_paused
                                         is false) -- game reports a chain-side
                                         maintenance pause; any write would revert
2. pending tx unreconciled           -> NO-OP, reconcile first
3. mission Resolving > 60s           -> resolveFleetMission   (permissionless, free)
4. incoming hostile fleet            -> ESCALATE, no proposal (fleet-visibility.incoming)
5-9. a four-band candidate pipeline (see below) -- deadline-driven storage overflow,
     then economically-scored building, then policy-declared research/ships/defense,
     then a locked declared target's unlock-chain step, else an explicit NO-OP.
```

**Rungs 0-4 are vetoes — safety, not strategy — and are untouched by Phase 2 of the
general-strategy-engine program** (docs/SPEC.md §5.4). Rung 3 remains a known,
documented gap: the frozen `Snapshot` model (`models.py`) carries `incoming_fleets` (for
rung 4's hostile-fleet detection) but no list of the *player's own* fleet missions and
their status, so `plan_next_action` accepts `resolvable_mission_ids` as an explicit,
caller-supplied parameter (default empty) rather than deriving it from the snapshot.

**Rungs 5-9 are a generate/filter/score/select pipeline, in `candidates.py`.** Before
Phase 2, each rung both decided the action *family* and hardcoded *which entity* in one
function. `candidates.py` splits generation (one pure function per family) from
selection (a small function per rung that replays the exact same priority order the
pre-Phase-2 ladder used) — see that module's docstring for the full architecture. This
module now only:

1. Calls the four `select_*` functions in the four-band precedence order below.
2. Attaches the winning `Candidate`'s runner-ups to the returned `Action.alternatives`
   (`AlternativeNote`, capped at `policy.strategy.max_alternatives`) — informational
   only, never a `Decision` input, never re-derived by `guard.py`.

**Four bands, in order** (docs/SPEC.md §5.4):

1. **Deadline-driven** — storage overflow (`candidates.select_storage_candidate`). A
   loss-avoidance deadline, not an ROI question; keeps precedence over everything else
   via `policy.storage.hours_to_cap_trigger`, exactly as rung 5 always has.
2. **Economically scored** — `candidates.select_building_candidate`, ascending payback
   hours among *legal* candidates. **The energy-first invariant stays a hard filter, not
   a score**: a mine candidate that would push post-upgrade `required` past `produced`
   is never generated by `candidates.generate_mine_candidates`, and the energy candidate
   (`candidates.generate_energy_candidates`) is generated in its place — identical
   semantics to the pre-Phase-2 ladder, now expressed as "never generated" instead of
   "generated then discarded." (This band also carries `policy.strategy.building_priority`
   infrastructure picks, which — deliberately, per that field's own docstring — win
   outright over a scored mine/energy candidate when declared; see `candidates.
   select_building_candidate`.)
3. **Policy-declared** — research, ships, defenses
   (`candidates.select_research_candidate` / `select_shipyard_candidate`), gated on
   `candidates.economy_on_track` exactly as rung 8 always was.
4. **Unlock-chain** (Phase 4, rung `8b`) — `candidates.select_unlock_chain_candidate`.
   Reached only when bands 1-3 produced nothing at all for any target planet, so it can
   never outrank the storage-overflow deadline and can never displace a scored economic
   or policy-declared candidate — see that function's docstring for why it is a separate
   rung rather than folded into band 2's `building_priority` branch. Proposes the
   shallowest buildable prerequisite toward a locked `ship_targets`/`defense_targets`/
   `research_priority` entry, always `score=None` (an unlock step's value is entirely in
   what it eventually enables, not something this codebase computes an ROI for).

**The two invariants that matter most, both derived from planet traits, never
hardcoded** (unchanged by Phase 2 — see `candidates.py` for where the logic now lives):

1. **Energy-first.** `candidates.generate_mine_candidates` computes `required` at the
   *post-upgrade* mine level via `calc.energy_balance` and compares it to `produced`
   (preferring the API's live `PlanetSnapshot.energy.produced`). If the upgrade would
   push `required > produced`, that mine is never generated as a candidate; the cheaper
   of Solar Plant / Solar Satellite substitutes it.
2. **Build order is derived from planet traits.** `candidates._mine_priority_order`
   ranks Metal / Crystal / Deuterium mines by `base_rate * live_multiplier_bps` ("value
   density"), so a planet's deuterium multiplier changes the opener without any
   per-planet branch. `candidates._cheapest_energy_choice` ranks Solar Plant vs. Solar
   Satellite by cost-per-energy-point using only *live* costs (`Entity.cost`) and the
   live `solarSatelliteEnergy` — never a hardcoded planet id. See
   `references/strategy-playbook.md` for the full derivation and a worked numeric
   example on both planet 664 and a hot-planet fixture.
"""

from __future__ import annotations

import json
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel

from veydrift_agent import candidates
from veydrift_agent.models import (
    Action,
    ActionKind,
    AlternativeNote,
    PlanetSnapshot,
    Policy,
    QueueKind,
    Snapshot,
)

app = typer.Typer(no_args_is_help=True, help="Decide the next action from a snapshot + policy.")


def _target_planets(snapshot: Snapshot, policy: Policy) -> list[PlanetSnapshot]:
    """`policy.planets == []` means "all snapshot planets" (docs/SPEC.md §5.6); otherwise
    the policy's own order is the priority order the ladder walks in.
    """
    if not policy.planets:
        return list(snapshot.planets)
    by_id = {p.planet_id: p for p in snapshot.planets}
    return [by_id[planet_id] for planet_id in policy.planets if planet_id in by_id]


# --------------------------------------------------------------------------------------
# Candidate -> Action, attaching `rule` and `alternatives`. Shared by every band below.
# --------------------------------------------------------------------------------------


def _why_not(alternative: candidates.Candidate, winner: candidates.Candidate) -> str:
    """`"payback 47h vs 31h"` when both the alternative and the winner are scored,
    otherwise the alternative's own `score_basis` (e.g. `"locked: needs Shipyard 2 (have
    0)"`, `"deadline: metal 1.4h from cap"`)."""
    if alternative.score is not None and winner.score is not None:
        return f"payback {alternative.score:.1f}h vs winner's {winner.score:.1f}h"
    return alternative.score_basis


def _finalize(
    winner: candidates.Candidate,
    alternatives: list[candidates.Candidate],
    rule: str,
    policy: Policy,
) -> Action:
    notes = [
        AlternativeNote(
            family=alt.family,
            entity_name=alt.action.entity_name,
            score=alt.score,
            why_not=_why_not(alt, winner),
        )
        for alt in alternatives[: policy.strategy.max_alternatives]
    ]
    return winner.action.model_copy(update={"rule": rule, "alternatives": notes})


def _next_building_action(planet: PlanetSnapshot, snapshot: Snapshot, policy: Policy, rule: str) -> Action | None:
    """The energy-first opener for a single planet. Thin wrapper around
    `candidates.select_building_candidate` — kept as a standalone, importable function
    (rather than inlined into `plan_next_action`) because `tests/test_plan.py` calls it
    directly to isolate rung 6's building-pick logic from the rest of the ladder."""
    winner, alternatives = candidates.select_building_candidate(snapshot, policy, planet)
    if winner is None:
        return None
    return _finalize(winner, alternatives, rule, policy)


# --------------------------------------------------------------------------------------
# The ladder.
# --------------------------------------------------------------------------------------


def plan_next_action(
    snapshot: Snapshot,
    policy: Policy,
    *,
    killswitch_active: bool = False,
    pending_tx_unreconciled: bool = False,
    resolvable_mission_ids: list[int] | None = None,
) -> Action:
    """Decide exactly one `Action` from `snapshot` + `policy`. First matching rung wins;
    `Action.rule` records which one fired (e.g. `"5:storage-overflow-spend"`) so the log
    is auditable without re-running the planner (docs/SPEC.md §5.4).

    `killswitch_active`, `pending_tx_unreconciled` and `resolvable_mission_ids` are not on
    `Snapshot` (that model is frozen and owned by WP1) — they are `tick.py`'s
    responsibility to discover (killswitch file, `agent-state.json`, `/missions`) and pass
    in. Defaults are the safe "nothing pending" state, so calling this with just a
    snapshot and policy is a legitimate offline planning call.
    """
    if killswitch_active:
        return Action(kind=ActionKind.HALT, rule="0:killswitch", rationale="KILLSWITCH file present; halting before any further action.")

    if not snapshot.health_ok and not snapshot.combat_only_degradation():
        reasons = ", ".join(snapshot.degradation_reasons) or "no reason given"
        return Action(
            kind=ActionKind.NOOP,
            rule="1:health-not-ok",
            rationale=(
                f"/health reported not ok / not ready ({reasons}); refusing to plan "
                "against a possibly-stale snapshot."
            ),
        )
    # Either health_ok, or a positively confirmed randomness/combat-only degradation
    # (Snapshot.combat_only_degradation) -- everything this codebase can act on is
    # healthy, and combat is unconditionally unreachable here regardless of policy, so
    # fall through to the rest of the ladder instead of NO-OPing on an irrelevant signal.

    if snapshot.game_paused:
        detail = ""
        if snapshot.game_maintenance is not None:
            age = snapshot.game_maintenance.pause_age_seconds
            since = snapshot.game_maintenance.paused_since
            if age:
                detail = f" ({age // 60}m{age % 60}s so far"
                detail += f", since {since.isoformat()})" if since else ")"
            elif since:
                detail = f" (since {since.isoformat()})"
        reasons = ", ".join(snapshot.degradation_reasons) or "game_paused"
        if policy.escalation.on_game_paused:
            return Action(
                kind=ActionKind.ESCALATE,
                rule="1b:game-paused",
                rationale=(
                    f"Game reports a chain-side maintenance pause{detail} "
                    f"(readiness.degradationReasons: {reasons}); escalating rather than "
                    "proposing an action that would revert on-chain."
                ),
            )
        return Action(
            kind=ActionKind.NOOP,
            rule="1b:game-paused",
            rationale=f"Game reports a maintenance pause{detail}; escalation.on_game_paused is false.",
        )

    if pending_tx_unreconciled:
        return Action(
            kind=ActionKind.NOOP,
            rule="2:pending-tx-unreconciled",
            rationale="A previous transaction has not been reconciled yet; resolving that takes priority over a new proposal.",
        )

    if resolvable_mission_ids:
        return Action(
            kind=ActionKind.RESOLVE_MISSION,
            function="resolveFleetMission",
            mission_id=resolvable_mission_ids[0],
            rule="3:mission-resolving",
            rationale=f"Mission {resolvable_mission_ids[0]} has been Resolving for >60s; resolveFleetMission is permissionless and free.",
        )

    if policy.escalation.on_incoming_fleet:
        hostiles = [fleet for fleet in snapshot.incoming_fleets if fleet.hostile]
        if hostiles:
            return Action(
                kind=ActionKind.ESCALATE,
                rule="4:incoming-hostile-fleet",
                rationale=(
                    f"{len(hostiles)} incoming hostile fleet(s) detected via "
                    "fleet-visibility.incoming; escalating to a human rather than proposing."
                ),
            )

    target_planets = _target_planets(snapshot, policy)

    # Band 1: deadline-driven storage overflow.
    storage_winner, storage_alternatives = candidates.select_storage_candidate(snapshot, policy, target_planets)
    if storage_winner is not None:
        rule = "5:storage-overflow-storage" if storage_winner.family == "storage" else "5:storage-overflow-spend"
        return _finalize(storage_winner, storage_alternatives, rule, policy)

    # Band 2: economically scored building (mine, energy-first-filtered).
    for planet in target_planets:
        if planet.queues.get(QueueKind.BUILDING) is None:
            candidate = _next_building_action(planet, snapshot, policy, rule="6:building-queue-empty")
            if candidate is not None:
                return candidate

    # Band 3: policy-declared research, then ships/defense.
    if snapshot.research_queue is None:
        research_winner, research_alternatives = candidates.select_research_candidate(snapshot, policy, target_planets)
        if research_winner is not None:
            return _finalize(research_winner, research_alternatives, "7:research-queue-empty", policy)

    shipyard_winner, shipyard_alternatives = candidates.select_shipyard_candidate(snapshot, policy, target_planets)
    if shipyard_winner is not None:
        return _finalize(shipyard_winner, shipyard_alternatives, "8:shipyard-idle", policy)

    # Band 4 (Phase 4 of the general-strategy-engine program, docs/SPEC.md §5.4): a
    # locked ship_targets/defense_targets/research_priority entry can never be produced
    # by bands 1-3 above (each correctly refuses to propose an entity the contract would
    # revert on) -- this is the only rung that proposes the *prerequisite* that would
    # unlock it instead. Reached only when nothing on bands 1-3 fired at all, so it can
    # never outrank storage overflow and can never displace a scored economic or
    # policy-declared research/ship/defense candidate -- see `candidates.
    # select_unlock_chain_candidate`'s docstring for why this is a separate rung rather
    # than folded into rung 6's `building_priority` branch.
    unlock_winner, unlock_alternatives = candidates.select_unlock_chain_candidate(snapshot, policy, target_planets)
    if unlock_winner is not None:
        return _finalize(unlock_winner, unlock_alternatives, "8b:unlock-chain", policy)

    # Band 5 (Phase 5c of the general-strategy-engine program, docs/SPEC.md §5.4):
    # non-combat fleet logistics -- Transport between the player's own planets, local
    # Harvest of a planet's own debris. Gated on `policy.actions.allow_fleet_noncombat`
    # (defaults False, so this band produces nothing at all under the default policy,
    # identical to pre-Phase-5c behaviour). Reached only after bands 1-4 produced nothing
    # for any target planet, same precedence rule band 4 (`8b:unlock-chain`) already
    # documents for itself: logistics is an "idle capacity" opportunity, never something
    # that should outrank a scored economic pick, a policy-declared research/ship/defense
    # target, or the storage-overflow deadline.
    logistics_winner, logistics_alternatives = candidates.select_logistics_candidate(snapshot, policy, target_planets)
    if logistics_winner is not None:
        rule = "8c:logistics-transport" if logistics_winner.family == "logistics-transport" else "8c:logistics-harvest"
        return _finalize(logistics_winner, logistics_alternatives, rule, policy)

    return Action(
        kind=ActionKind.NOOP,
        rule="9:no-match",
        rationale=(
            "No ladder rung produced a proposal: queues busy, or policy disallows the "
            "available actions, or no entity data was present for any target planet."
        ),
    )


# --------------------------------------------------------------------------------------
# CLI — offline: reads a Snapshot and a Policy from files. `tick.py` (WP3) is the wired,
# online caller; this is a debugging / dry-run entrypoint that does not depend on it.
# --------------------------------------------------------------------------------------


@app.command()
def run(
    snapshot: Path = typer.Option(..., "--snapshot", help="Path to a Snapshot JSON file."),  # noqa: B008
    policy: Path = typer.Option(..., "--policy", help="Path to a Policy JSON file."),  # noqa: B008
    killswitch: bool = typer.Option(False, help="Simulate a present KILLSWITCH file."),
    pending_tx: bool = typer.Option(False, "--pending-tx", help="Simulate an unreconciled pending tx."),
    json_output: bool = typer.Option(False, "--json", help="Print the Action as JSON instead of a panel."),
) -> None:
    """Decide the next action from a snapshot + policy file. Offline; no network calls."""
    console = Console()
    try:
        snapshot_model = Snapshot.model_validate(json.loads(snapshot.read_text()))
        policy_model = Policy.model_validate(json.loads(policy.read_text()))
    except (OSError, ValueError) as exc:
        console.print(f"[red]failed to load snapshot/policy: {exc}[/red]")
        raise typer.Exit(code=4) from exc

    action = plan_next_action(
        snapshot_model,
        policy_model,
        killswitch_active=killswitch,
        pending_tx_unreconciled=pending_tx,
    )

    if json_output:
        typer.echo(action.model_dump_json(indent=2))
        return

    body = [f"rule:      {action.rule}", f"kind:      {action.kind.value}"]
    if action.function:
        body.append(f"function:  {action.function}(planet={action.planet_id}, entity={action.entity_id})")
    if action.target_level is not None:
        body.append(f"target:    level {action.target_level}")
    if action.quantity is not None:
        body.append(f"quantity:  {action.quantity}")
    if action.cost.metal or action.cost.crystal or action.cost.deuterium:
        body.append(f"cost:      M {action.cost.metal}  C {action.cost.crystal}  D {action.cost.deuterium}")
    body.append(f"why:       {action.rationale}")
    if action.alternatives:
        body.append(f"alts:      {len(action.alternatives)} considered and not selected (see --json for detail)")
    console.print(Panel("\n".join(body), title=f"vd plan run -- {action.kind.value}"))


if __name__ == "__main__":
    app()
